services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - cache:/var/task/.cache
  esgvoc:
    build:
      context: .
      dockerfile: ./Dockerfile-esgvoc
    volumes:
      - cache:/cache

volumes:
  cache: