services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - cache:/root/.local/share/esgvoc
  esgvoc:
    build:
      context: .
      dockerfile: ./Dockerfile-esgvoc
    volumes:
      - cache:/root/.local/share/esgvoc

volumes:
  cache: