FROM public.ecr.aws/sam/build-python3.12:latest-x86_64

RUN pip install esgvoc
RUN esgvoc install

# Need to share volume in ECS
VOLUME ["/root/.local/share/esgvoc"]

ENTRYPOINT ["tail", "-f", "/dev/null"]